version: '3.8'

services:
  postgres_container: 
    image: postgres:15
    container_name: postgres_container
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: booking-hotel
 